# Libraries

In [1]:
! pip install mlxtend

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.3.5)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.2)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.21.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.4.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.1->mlxtend) (4.2.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->mlxtend) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=1.5.1->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (1.1.0)

In [2]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Data Mining/HW5/Hackathon_Working_Data.csv')
df

,MONTH,STORECODE,DAY,BILL_ID,BILL_AMT,QTY,VALUE,PRICE,GRP,SGRP,SSGRP,CMP,MBRD,BRD
0,M1,N1,4,T375,225.0,1.0,225.0,225.0,BUTTER MARGR (4/94),BUTTER,SALTED,G C M M F,AMUL,AMUL
1,M1,N1,4,T379,95.0,1.0,95.0,95.0,CONFECTIONERY - ECLAIRS,CONFECTIONERY - ECLAIRS,CONFECTIONERY - ECLAIRS,PARLE PRODS,MELODY,MELODY CHOCOLATY
2,M1,N1,4,T381,10.0,1.0,10.0,10.0,CHOCOLATE,CHOCOLATE PANNED,CHOCOLATE PANNED,MONDELEZ INTERNATIONAL,CADBURY SHOTS,CADBURY SHOTS
3,M1,N1,4,T382,108.0,1.0,108.0,108.0,PACKAGED TEA,MAIN PACKS,MAIN PACKS,GUJ TEA PROCESSORS,WAGH BAKRI,WAGH BAKRI INSTANT
4,M1,N1,4,T384,19.0,1.0,19.0,19.0,ALL IODISED SALT,POWDERED SALT,POWDERED SALT,TATA CHEM,TATA,TATA SALT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26980,M3,N10,31,T5999,10.0,1.0,10.0,10.0,BISCUITS - CORE & NON CORE,NON-SALT CRACKER,NON-SALT CRACKER,PARLE PRODS,PARLE KRACK JACK,PARLE KRACK JACK
26981,M3,N10,31,T6007,88.0,1.0,10.0,10.0,BISCUITS - CORE & NON CORE,MARIE,MARIE,PARLE PRODS,PARLE MARIE,PARLE MARIE
26982,M3,N10,31,T6007,88.0,2.0,20.0,10.0,BISCUITS - CORE & NON CORE,GLUCOSE,GLUCOSE,PARLE PRODS,PARLE-G,PARLE-G
26983,M3,N10,31,T6007,88.0,1.0,58.0,58.0,CLEANERS - GLASS,LIQUIDS,LIQUIDS,RECKITT BENCKISER,COLIN,COLIN
26984,M3,N10,31,T6013,15.0,1.0,15.0,15.0,BISCUITS - CORE & NON CORE,SWEET/COOKIES,SWEET/COOKIES,SAJ INDS,BISK FARM,BISK FARM JUST GINGER

# Part b

there is no missing value

In [4]:
df.dropna(inplace=True)
df

,MONTH,STORECODE,DAY,BILL_ID,BILL_AMT,QTY,VALUE,PRICE,GRP,SGRP,SSGRP,CMP,MBRD,BRD
0,M1,N1,4,T375,225.0,1.0,225.0,225.0,BUTTER MARGR (4/94),BUTTER,SALTED,G C M M F,AMUL,AMUL
1,M1,N1,4,T379,95.0,1.0,95.0,95.0,CONFECTIONERY - ECLAIRS,CONFECTIONERY - ECLAIRS,CONFECTIONERY - ECLAIRS,PARLE PRODS,MELODY,MELODY CHOCOLATY
2,M1,N1,4,T381,10.0,1.0,10.0,10.0,CHOCOLATE,CHOCOLATE PANNED,CHOCOLATE PANNED,MONDELEZ INTERNATIONAL,CADBURY SHOTS,CADBURY SHOTS
3,M1,N1,4,T382,108.0,1.0,108.0,108.0,PACKAGED TEA,MAIN PACKS,MAIN PACKS,GUJ TEA PROCESSORS,WAGH BAKRI,WAGH BAKRI INSTANT
4,M1,N1,4,T384,19.0,1.0,19.0,19.0,ALL IODISED SALT,POWDERED SALT,POWDERED SALT,TATA CHEM,TATA,TATA SALT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26980,M3,N10,31,T5999,10.0,1.0,10.0,10.0,BISCUITS - CORE & NON CORE,NON-SALT CRACKER,NON-SALT CRACKER,PARLE PRODS,PARLE KRACK JACK,PARLE KRACK JACK
26981,M3,N10,31,T6007,88.0,1.0,10.0,10.0,BISCUITS - CORE & NON CORE,MARIE,MARIE,PARLE PRODS,PARLE MARIE,PARLE MARIE
26982,M3,N10,31,T6007,88.0,2.0,20.0,10.0,BISCUITS - CORE & NON CORE,GLUCOSE,GLUCOSE,PARLE PRODS,PARLE-G,PARLE-G
26983,M3,N10,31,T6007,88.0,1.0,58.0,58.0,CLEANERS - GLASS,LIQUIDS,LIQUIDS,RECKITT BENCKISER,COLIN,COLIN
26984,M3,N10,31,T6013,15.0,1.0,15.0,15.0,BISCUITS - CORE & NON CORE,SWEET/COOKIES,SWEET/COOKIES,SAJ INDS,BISK FARM,BISK FARM JUST GINGER

# Part c

In [5]:
df['Trans_ID'] = df['STORECODE'] + '_' + df['BILL_ID']
df.head()

,MONTH,STORECODE,DAY,BILL_ID,BILL_AMT,QTY,VALUE,PRICE,GRP,SGRP,SSGRP,CMP,MBRD,BRD,Trans_ID
0,M1,N1,4,T375,225.0,1.0,225.0,225.0,BUTTER MARGR (4/94),BUTTER,SALTED,G C M M F,AMUL,AMUL,N1_T375
1,M1,N1,4,T379,95.0,1.0,95.0,95.0,CONFECTIONERY - ECLAIRS,CONFECTIONERY - ECLAIRS,CONFECTIONERY - ECLAIRS,PARLE PRODS,MELODY,MELODY CHOCOLATY,N1_T379
2,M1,N1,4,T381,10.0,1.0,10.0,10.0,CHOCOLATE,CHOCOLATE PANNED,CHOCOLATE PANNED,MONDELEZ INTERNATIONAL,CADBURY SHOTS,CADBURY SHOTS,N1_T381
3,M1,N1,4,T382,108.0,1.0,108.0,108.0,PACKAGED TEA,MAIN PACKS,MAIN PACKS,GUJ TEA PROCESSORS,WAGH BAKRI,WAGH BAKRI INSTANT,N1_T382
4,M1,N1,4,T384,19.0,1.0,19.0,19.0,ALL IODISED SALT,POWDERED SALT,POWDERED SALT,TATA CHEM,TATA,TATA SALT,N1_T384

# Part d

In [6]:
df2 = (df.groupby(['Trans_ID', 'GRP'])['QTY'].sum().unstack().fillna(0).reset_index().set_index('Trans_ID'))
df2

GRP,AFTER SHAVE LOTIONS,AGARBATTI & DHOOPBATTI,ALL AIR FRESHNERS(01/03),ALL IODISED SALT,ANTACIDS,ANTISEPTIC CREAMS,ANTISEPTIC LIQUIDS (4/97),BABY FOODS,BABY OILS / MASSAGE OILS,BATTERIES,...,SUGAR SUBSTITUTE (11/05),TALCUM POWDERS,TOILET SOAPS (04/00),TOOTH BRUSH (7/93),TOOTH PASTES,TOOTH POWDERS,TWIN BLADES,VANASPATI CONS PACK (8/94),VERMICELLI & NOODLE,WASHING POWDERS/LIQUIDS
Trans_ID,,,,,,,,,,,,,,,,,,,,,
N10_T1038,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
N10_T1039,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
N10_T1040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
N10_T1043,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
N10_T1048,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N9_T940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
N9_T95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
N9_T953,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0
N9_T96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
N9_T99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Part e

In [7]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

main_df = df2.applymap(encode_units)
main_df.dropna(inplace=True)

# Part f

In [8]:
frequent_itemsets = apriori(main_df, min_support=0.01, use_colnames=True)
print(frequent_itemsets)

     support                                           itemsets
0   0.033361                                 (ALL IODISED SALT)
1   0.013863                                        (BEVERAGES)
2   0.283564                       (BISCUITS - CORE & NON CORE)
3   0.023723                                (BREAKFAST CEREALS)
4   0.038846                             (BUTTER MARGR  (4/94))
5   0.018459                             (CHEESE        (4/94))
6   0.090370                                        (CHOCOLATE)
7   0.020609                                 (CLEANERS - FLOOR)
8   0.012232                                (CLEANERS - TOILET)
9   0.046631                               (CLEANERS - UTENSIL)
10  0.020832                        (COCONUT OIL PKTYP (08/02))
11  0.011862                                           (COFFEE)
12  0.020239                       (CONFECTIONERY - TOFFEE/HBC)
13  0.024242                             (DETERGENT CAKES/BARS)
14  0.011268                             (DIAPERS       (8/93))
15  0.014382                             (HAIR DYES     (1/76))
16  0.014679                             (HAIR OILS PKTP(8/02))
17  0.024316                                  (KETCHUPS/SAUCES)
18  0.011046                      (LIQUID TOILET SOAPS  (8/93))
19  0.043220                             (PACKAGED ATTA (1/95))
20  0.023723                               (PACKAGED PURE GHEE)
21  0.069612                                     (PACKAGED TEA)
22  0.016087                           (PRE-POST WASH PRODUCTS)
23  0.018830                                     (READY TO EAT)
24  0.061606                    (REFINED EDIBLE OILS-ALL PACKS)
25  0.106086                              (SALTY SNACKS (2/97))
26  0.014011                                 (SANITARY NAPKINS)
27  0.021351                            (SHAMPOO - BY SEGMENTS)
28  0.018978                                      (SKIN CREAMS)
29  0.078879                                   (SPICES (03/04))
30  0.059901                             (TOILET SOAPS (04/00))
31  0.046334                                     (TOOTH PASTES)
32  0.087479                              (VERMICELLI & NOODLE)
33  0.076433                          (WASHING POWDERS/LIQUIDS)
34  0.019720            (BISCUITS - CORE & NON CORE, CHOCOLATE)
35  0.011194   (BISCUITS - CORE & NON CORE, CLEANERS - UTENSIL)
36  0.014679         (BISCUITS - CORE & NON CORE, PACKAGED TEA)
37  0.011343  (BISCUITS - CORE & NON CORE, REFINED EDIBLE OI...
38  0.025651  (SALTY SNACKS (2/97), BISCUITS - CORE & NON CORE)
39  0.010675       (BISCUITS - CORE & NON CORE, SPICES (03/04))
40  0.013715  (BISCUITS - CORE & NON CORE, TOILET SOAPS (04/...
41  0.012677         (BISCUITS - CORE & NON CORE, TOOTH PASTES)
42  0.024390  (VERMICELLI & NOODLE, BISCUITS - CORE & NON CORE)
43  0.014975  (WASHING POWDERS/LIQUIDS, BISCUITS - CORE & NO...
44  0.014308      (WASHING POWDERS/LIQUIDS, CLEANERS - UTENSIL)
45  0.012158               (TOILET SOAPS (04/00), TOOTH PASTES)
46  0.015939    (WASHING POWDERS/LIQUIDS, TOILET SOAPS (04/00))
47  0.011120            (WASHING POWDERS/LIQUIDS, TOOTH PASTES)

# Part g

In [9]:
rules = association_rules(frequent_itemsets, metric="lift")
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(BISCUITS - CORE & NON CORE),(CLEANERS - UTENSIL),0.283564,0.046631,0.011194,0.039477,0.846593,-0.002028,0.992553
1,(CLEANERS - UTENSIL),(BISCUITS - CORE & NON CORE),0.046631,0.283564,0.011194,0.240064,0.846593,-0.002028,0.942757
2,(SALTY SNACKS (2/97)),(BISCUITS - CORE & NON CORE),0.106086,0.283564,0.025651,0.241789,0.852677,-0.004432,0.944903
3,(BISCUITS - CORE & NON CORE),(SALTY SNACKS (2/97)),0.283564,0.106086,0.025651,0.090458,0.852677,-0.004432,0.982817
4,(BISCUITS - CORE & NON CORE),(TOILET SOAPS (04/00)),0.283564,0.059901,0.013715,0.048366,0.807437,-0.003271,0.987879

# Part i

In [10]:
rules[ (rules['lift'] >= 2) &
       (rules['confidence'] >= 0.3) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
11,(CLEANERS - UTENSIL),(WASHING POWDERS/LIQUIDS),0.046631,0.076433,0.014308,0.306836,4.014466,0.010744,1.332394